### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by ademenev** [ReactiveKit/ReactiveAppKit#4]
Podfile

```
target 'TestApp'
use_frameworks!

pod 'ReactiveKit', '~> 2.0'
pod 'Alamofire', '~> 3.3'
pod 'JSONCodable', '~> 2.1'
pod 'AlamofireReactive', '>= 1.0'
pod 'AlamofireImage', '~> 2.0'
pod 'ReactiveAppKit', '~> 2.0'
```

```
pod --version
1.0.1
```

```
pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-TestApp `: (``)

Finding Podfile changes
  A ReactiveAppKit
  - Alamofire
  - AlamofireImage
  - AlamofireReactive
  - JSONCodable
  - ReactiveKit

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `ReactiveAppKit (~> 2.0)`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:57:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by gm2211** [comment]
+1 - Still broken

I think `pod trunk push ReactiveAppKit.podspec` needs to be done @srdanrasic

**Comment by srdanrasic** [comment]
ReactiveAppKit has been converted to Bond almost a year ago :)
 https://github.com/ReactiveKit/Bond :)
